title: Components
email: loeschef@janelia.hhmi.org
description: >- # this means to ignore newlines until "baseurl:"
  Some 3D printing, laser cutting, PCBs used in the lab.

repository: reiserlab/Component-Designs

# Build settings
remote_theme: pmarsceill/just-the-docs
search_enabled: true
color_scheme: "components"

kramdown:
  toc_levels: "1,2"

# relative_links:
#   enabled: true

# change location of data directory from /_data to /assets/data
data_dir: assets/data
